# Demo how to use minikube as CI env with github Actions
#
# Usage:
# git checkout -b minikube
# git push

name: minikube
on:
  workflow_dispatch:
  push:
    branches:
      - 'minikube'
    paths-ignore:
      - '**/README.md'

env:
  APP: weather-forecast-api
  IMAGE_NAME: minikube/weather-forecast-api

jobs:
  minikube-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster
        run: kubectl get all -A

      - name: Build local image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          cd src
          docker build -f ./Dockerfile -t ${{ env.IMAGE_NAME }} .
          echo -n "verifying images:"
          docker image ls ${{ env.IMAGE_NAME }}
          eval $(minikube docker-env --unset)

      - name: Deploy app to minikube
        run: |
          kubectl apply -f ./deploy/RollingUpdate/manifest.yaml
          kubectl wait --for=condition=Ready pods --timeout=300s -l "app=${{ env.APP }}"

      - name: Test service URLs
        run: |
          minikube service list
          minikube service ${{ env.APP }} --url
          echo "------------------opening the service------------------"
          curl -sSL $(minikube service ${{ env.APP }} --url)/
          minikube delete
